const products = [

  {'_id': '1',
    'name': 'corssair scimitar PRO',
    'image': '/images/corsair.jpg',
    'description':
      'votre casque pour le jeu haut performances préférée offre des fonctionnalités plus précises que jamais. En plus du surround du 7.1',
    'brand': 'corssair',
    'category': 'Electronics',
    'price': 1800,
    'countInStock': 1,
    'rating': 4.5,
    'numReviews': 50,
  },
  {'_id': '2',
    'name': 'Logitech G-502 hero',
    'image': '/images/G502.jpg',
    'description':
      "Votre souris pour le jeu hautes performances préférée offre des fonctionnalités plus précises que jamais. Personnalisez l'éclairage RVB en fonction de votre style ",
    'brand': 'Logitech',
    'category': 'Electronics',
    'price': 899,
    'countInStock': 2,
    'rating': 5,
    'numReviews': 12,
  },
  {'_id': '3',
    'name': 'Razer Balistic sans-fil',
    'image': '/images/Balistic.jpg',
    'description':
      "Votre souris pour le jeu hautes performances préférée offre des fonctionnalités plus précises que jamais. Et en plus sans fil ",
    'brand': 'razer',
    'category': 'Electronics',
    'price': 1150,
    'countInStock': 1,
    'rating': 3,
    'numReviews': 5,
  },
  {'_id': '4',
    'name': 'Souris Cougar',
    'image': '/images/COUGAR.png',
    'description':
      "Votre souris pour le jeu hautes performances préférée offre des fonctionnalités plus précises que jamais.",
    'brand': 'cougar',
    'category': 'Electronics',
    'price': 700,
    'countInStock': 3,
    'rating': 3.5,
    'numReviews': 6,
  },
  {'_id': '5',
    'name': 'Hyper-x cloud 2 ',
    'image': '/images/cloud2.jpg',
    'description':
      "Votre casque pour les jeux a hauts performences surtout les fps . Doté de plus du surround 7.1",
    'brand': 'hyperx',
    'category': 'Electronics',
    'price': 1300,
    'countInStock': 10,
    'rating': 4.5,
    'numReviews': 20,
  },
  {'_id': '6',
    'name': 'Logitech G432 7.1',
    'image': '/images/G432.jpg',
    'description':
      "Votre casque pour les jeux a hauts performences surtout les fps . Doté de plus du surround 7.1",
    'brand': 'logitech',
    'category': 'Electronics',
    'price': 999,
    'countInStock': 0,
    'rating': 2.5,
    'numReviews': 5,
  },
  {'_id': '7',
    'name': 'Corsair virtuose rgb',
    'image': '/images/casquecorsair.jpg',
    'description':
      "Votre casque pour les jeux a hauts performences surtout les fps . Doté de plus du surround 7.1",
    'brand': 'corsair',
    'category': 'Electronics',
    'price': 1100,
    'countInStock': 3,
    'rating':4,
    'numReviews': 2,
  },
  {'_id': '8',
    'name': 'RAZER Kraken Vert',
    'image': '/images/casquerazer.jpg',
    'description':
      "Votre casque pour les jeux a hauts performences surtout les fps . Doté de plus du surround 7.1",
    'brand': 'razer',
    'category': 'Electronics',
    'price': 1480,
    'countInStock': 5,
    'rating':4.5,
    'numReviews': 5,
  },
  
]


export default products
